config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users
  root "users#index"

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show]
  end

  resources :posts, only: [:new, :create] do
    resources :comments, only: [:new, :create]
    resources :likes, only: [:create]
  end
  
  resources :posts, only: [:destroy]
  resources :comments, only: [:destroy]
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Post
    can :read, Comment
    return unless user.present?

    can :manage, Post, author: user
    can :manage, Comment, author: user
    return unless user.role == 'admin'

    can :manage, :all
  end
end

app/models/application_record.rb
# ApplicationRecord class
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post

  after_save :update_posts_comments_counter
  after_destroy :update_posts_comments_counter

  private

  def update_posts_comments_counter
    post.update(comments_counter: post.comments.count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post

  after_save :update_posts_likes_counter
  after_destroy :update_posts_likes_counter

  private

  def update_posts_likes_counter
    post.update(likes_counter: post.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_save :update_posts_counter
  after_destroy :update_posts_counter

  def most_recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def update_posts_counter
    author.update(posts_counter: author.posts.count)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable
  has_many :posts, foreign_key: 'author_id', dependent: :destroy
  has_many :comments, foreign_key: 'author_id', dependent: :destroy
  has_many :likes, foreign_key: 'author_id', dependent: :destroy

  def most_recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :bio, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :bio, :email, :password, :current_password)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    post = Post.find(params[:post_id])
    @comment = post.comments.new(author: post.author, **comment_parameters)
    if @comment.save
      redirect_to user_post_path(post.author, post)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    redirect_back(fallback_location: root_path)
  end

  private

  def comment_parameters
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    post = Post.find(params[:post_id])
    @like = post.likes.new(author: post.author)
    if @like.save
      redirect_to user_post_path(post.author, post)
    else
      render :new, status: :unprocessable_entity
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.includes(:author).where(author_id: params[:user_id])
    @user_id = params[:user_id]
    @user = User.find(params[:user_id])
  end

  def show
    @user_id = params[:user_id]
    @post_id = params[:id]
    @post = Post.find(params[:id])
    @comment = Comment.new
    @like = Like.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(**post_parameters, likes_counter: 0, comments_counter: 0)
    if @post.save
      redirect_to user_post_path(@post.author, @post)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to root_path, status: :see_other
  end

  private

  def post_parameters
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @current = @users.first
  end

  def show
    @id = params[:id]
    @current_user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
# ApplicationHelper module
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<%= render "shared/user", user: @user %>

<% if @posts.empty? %>
        <p>No post</p>
    <% end %>
    <% @posts.each do |post| %>
        <%= render "shared/post", post: post %>
        <%= render "shared/comment", comments: post.most_recent_comments[0, 5] %>
    <% end %>

<button class="btn-pagination" type="button">Pagination</button>

app/views/posts/new.html.erb
<%= form_with model:@post, html: { class: 'post-form'} do |form|%>
  <h1>Create Post</h1>
  <%=form.label :title%>
  <%=form.text_field :title, class: 'post-title'%>
  <%=form.label "Post"%>
  <%=form.text_area :text, class: 'post-text'%>
  <%=form.submit "Post", class: 'btn-add-post'%>
<%end%>

app/views/posts/show.html.erb
<section class="posts-show " >
  <div class="post-card">
    <h2><%=@post.title%> by <%=@post.author.name%></h2>
    <div>Comments: <%=@post.comments_counter%>, Likes: <%=@post.likes_counter%></div>
    <div><%=@post.text%></div>
    <%= button_to "Like", post_likes_path(@post), method: :post, class: 'btn-like' %>
    <% if can? :destroy, @post %>
      <%= button_to "Delete Post", post_path(@post), method: :delete, class: 'bth-delete-post'%>
    <%end%>
  </div>
</section>
  <%= render 'shared/comment', comments: @post.comments[0, 10]%>
  <%= render 'shared/comment_form', post: @post, comment: @comment%>

app/views/shared/_comment.html.erb
<ul class="comments-list">
  <% if comments.empty? %>
      <p>No comment</p>
  <% else %>
    <% comments.each do |comment| %>
      <li class="comment-card">
        <div><%=comment.author.name%> : <%=comment.text%></div>
    
        <% if can? :destroy, comment %>
          <%= button_to "Delete Comment", comment_path(comment), method: :delete, class: 'btn-delete-comment'%>
        <%end%>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/shared/_comment_form.erb
<%= form_with model:([post, comment]), html: { class: 'comment-form'} do |form|%>
  <%=form.label "Enter Comment:"%>
  <%=form.text_area :text, class: 'comment-text'%>
  <%=form.submit "Comment", class: 'btn-comment'%>
<%end%>

app/views/shared/_post.html.erb
<%=link_to user_post_path(post.author, post) do%>
  <div class=post-card>
    <h2><%=post.title%></h2>
    <div><%=post.text[0, 100]%><%='...' if post.text[101]%></div>
    <div class="comments-and-likes">Comments: <%=post.comments_counter%>, Likes: <%=post.likes_counter%></div>
  </div>
<%end%>

app/views/shared/_user.html.erb
<div class="user-card">
  <img class="" src="<%= user.photo %>" alt="profile-<%= user.name %>" width="150" height="150">
  <%= link_to user do %>
    <h2><%=user.name%></h2>
    <div class="post-count>">Number of posts: <%=user.posts_counter%></div>
  <%end%>
</div>

app/views/users/index.html.erb
<h1 class='greeting'>Welcome</h1>
<%= button_to "Logout", destroy_user_session_path, method: :delete, class: 'btn-logout'%>
<div class='btn-new-post'><%= link_to "Create Post", new_post_path%></div>
<ul>
<% @users.each do |user| %>
  <li>
    <%= render 'shared/user', user: user%>
  </li>
<% end %>
</ul>

app/views/users/show.html.erb
<%= render 'shared/user', user: @current_user%>
<section class="bio-section">
  <h2>Bio</h2>
  <div class="bio-description"><%=@current_user.bio%></div>
</section>

<section class="posts-section">
  <ul>
    <% if @current_user.most_recent_posts.empty?%>
        <p class="empty-post">No posts</p>
        <%else%>
    <% @current_user.most_recent_posts.each do |post| %> 
        <li class="posts-list">
          <%=render 'shared/post', post: post%>
        </li>
        <% end %>
      <%end%>
  </ul>
</section >

<button class="btn-all-posts"><%= link_to "See all posts", user_posts_path(@current_user) %></button>